name: deepl
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pytorch
  - jupyter
  - pip
  - tqdm
  - pip:
    - torchinfo
    - librosa
    - d2l==1.0.0a1.post0